// Pure: renders the managed block. Output is deterministic (no timestamps) so
// `check` can compare it byte for byte.
import { ProjectSummary } from "./projectMap";
import { RULES_FILE, TOOL_DIR } from "./config";

export const BLOCK_START = "<!-- agent-context:start -->";
export const BLOCK_END = "<!-- agent-context:end -->";

export interface RenderOptions {
  maxModelsPerApp: number;
}

const code = (s: string): string => "`" + s.replace(/`/g, "'") + "`";
const cell = (s: string): string => s.replace(/\|/g, "\\|");

/** Drops HTML comments (template guidance) and a leading H1, trims blank edges. */
export function cleanRules(markdown: string): string {
  return markdown
    .replace(/\r\n/g, "\n")
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/[ \t]+$/gm, "")
    .replace(/^[ \t]*[-*]$/gm, "")
    .replace(/^\s*# [^\n]*\n/, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

/** Nests the rules' headings under "## Project rules" (code fences untouched). */
export function demoteHeadings(markdown: string): string {
  let fence = false;
  return markdown
    .split("\n")
    .map((line) => {
      if (/^\s*(```|~~~)/.test(line)) {
        fence = !fence;
      }
      return !fence && /^#{1,5} /.test(line) ? `#${line}` : line;
    })
    .join("\n");
}

export function renderProjectMap(s: ProjectSummary, opts: RenderOptions): string {
  const out: string[] = ["## Project map", ""];
  const facts = [
    s.settings.length > 0 ? `settings: ${s.settings.map(code).join(", ")}` : undefined,
    s.rootUrls ? `root URLconf: ${code(s.rootUrls)}` : undefined,
    `${s.apps.length} app${s.apps.length === 1 ? "" : "s"}`,
  ].filter(Boolean);
  out.push(`Django project · ${facts.join(" · ")}`, "");
  if (s.referenceApp) {
    out.push(
      `New apps must be cloned from the approved reference app ${code(s.referenceApp)} with the \`django-new-app\` skill. Never use \`startapp\`.`,
      ""
    );
  }
  if (s.apps.length > 0) {
    out.push("| App | Models | URL prefix | Depends on |", "| --- | --- | --- | --- |");
    for (const a of s.apps) {
      const shown = a.models.slice(0, opts.maxModelsPerApp);
      const more = a.models.length - shown.length;
      const models = shown.length > 0 ? shown.join(", ") + (more > 0 ? ` +${more} more` : "") : "—";
      const deps = a.dependsOn.length > 0 ? a.dependsOn.map((d) => d.slice(d.lastIndexOf("/") + 1)).join(", ") : "—";
      const name = code(a.dir) + (a.dir === s.referenceApp ? " (reference)" : "");
      out.push(`| ${cell(name)} | ${cell(models)} | ${a.urlPrefix ? code(a.urlPrefix) : "—"} | ${cell(deps)} |`);
    }
    out.push("");
  }
  return out.join("\n");
}

export function renderBlock(rules: string | undefined, summary: ProjectSummary | undefined, opts: RenderOptions): string {
  const parts: string[] = [
    BLOCK_START,
    `<!-- Generated by Agent Context Sync. Do not edit between these markers: edit ${RULES_FILE}, then run \`node ${TOOL_DIR}/cli.js sync\`. -->`,
    "",
  ];
  const body = rules !== undefined ? demoteHeadings(cleanRules(rules)) : "";
  if (body) {
    parts.push("## Project rules", "", body, "");
  }
  if (summary?.isDjango) {
    parts.push(renderProjectMap(summary, opts));
  }
  parts.push(
    `After adding or removing apps, models or URL includes, run \`node ${TOOL_DIR}/cli.js sync\` so every agent's instructions stay current.`,
    BLOCK_END
  );
  return parts.join("\n");
}
