// Embeds ci/agent-guardrails.yml as src/generated/ciTemplate.ts so the CLI that
// is installed into a project can write the workflow without the extension's
// files. src/generated/ is git-ignored and rebuilt before every compile.
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const out = path.join(root, "src", "generated");
fs.mkdirSync(out, { recursive: true });
const ci = fs.readFileSync(path.join(root, "ci", "agent-guardrails.yml"), "utf8");
fs.writeFileSync(
  path.join(out, "ciTemplate.ts"),
  "// GENERATED by scripts/generate.js from ci/agent-guardrails.yml. Do not edit.\n" +
    `export const CI_WORKFLOW = ${JSON.stringify(ci)};\n`
);
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
fs.writeFileSync(
  path.join(out, "version.ts"),
  "// GENERATED by scripts/generate.js from package.json. Do not edit.\n" +
    `export const STUDIO_VERSION = ${JSON.stringify(pkg.version)};\n`
);
